#Makefile JAVA, não faça caca tentando compilar C ou C++ com isso, sir JV


#####		PASTAS

PASTA_CODIGOS=src
PASTA_BINARIOS=bin

PASTA_ESCALONADOR=Escalonador



PASTA_GERAL=Geral
PASTA_FILA=Fila




PASTA_INTERFACE=Interface



######		ARQUIVOS
MAIN=Main.java

#Escalonador
ESCALONADOR=Escalonador.java
PROCESSO=Processo.java
CPU=CPU.java

#Fila
FILA=Fila.java

######		Variáveis necessárias para compilação

COMPILADOR=javac
JAVA=java
DEFINE_DIRETORIO_DE_COMPILADOS=-d


######		Regras
all: $(MAIN)
	@echo "Compilação terminada com sucesso!"

debug:

run:
	cd $(PASTA_BINARIOS); $(JAVA) $(MAIN:.java=)


$(MAIN): $(CPU)
	cp $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/*.java ./
	$(COMPILADOR) $(PASTA_CODIGOS)/$(MAIN) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	rm $(ESCALONADOR) $(PROCESSO) $(CPU)


#Libs
$(FILA):
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_GERAL)/$(PASTA_FILA)/$(FILA) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)

$(PROCESSO): $(FILA)
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(PROCESSO) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	
$(CPU): $(PROCESSO) $(FILA)
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(CPU) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	
