#Makefile JAVA, não faça caca tentando compilar C ou C++ com isso, sir JV


#####		PASTAS

PASTA_CODIGOS=src
PASTA_BINARIOS=bin

PASTA_ESCALONADOR=Escalonador



PASTA_GERAL=Geral
PASTA_FILA=Fila
PASTA_EntradaSaida=E-S




PASTA_INTERFACE=Interface



######		ARQUIVOS
MAIN=Main.java
CRIADOR_DE_PROCESSOS=CriadorDeProcessos.java

##Escalonador
ESCALONADOR=Escalonador.java
PROCESSO=Processo.java
CPU=CPU.java
TIPO_CPU=TipoCPU.java

##Geral

#Fila
FILA=Fila.java
#Entrada e Saída
ESCRITOR=Escritor.java

##Interface
INTERFACE=Interface.java


######		Variáveis necessárias para compilação

COMPILADOR=javac
JAVA=java
DEFINE_DIRETORIO_DE_COMPILADOS=-d


######		Regras
all: $(MAIN)
	cp $(PASTA_BINARIOS)/* ./
	jar cfm Executavel.jar ./Manifest.txt *.class
	chmod +x Executavel.jar
	@echo "Compilação terminada com sucesso!"

debug:

run:
	cd $(PASTA_BINARIOS); $(JAVA) $(MAIN:.java=)


$(MAIN): $(CPU) $(ESCALONADOR)
	cp $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/*.java ./
	cp $(PASTA_CODIGOS)/$(PASTA_INTERFACE)/$(INTERFACE) ./
	cp $(PASTA_CODIGOS)/$(PASTA_GERAL)/$(PASTA_FILA)/$(FILA) ./
	cp $(PASTA_CODIGOS)/$(CRIADOR_DE_PROCESSOS) ./
	$(COMPILADOR) $(PASTA_CODIGOS)/$(MAIN) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	rm $(INTERFACE)
	rm $(CRIADOR_DE_PROCESSOS)
	rm $(ESCALONADOR) $(PROCESSO) $(CPU) $(FILA)


#Libs
$(FILA):
	cp $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(CPU) ./
	cp $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(PROCESSO) ./
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_GERAL)/$(PASTA_FILA)/$(FILA) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	rm ./$(CPU)
	rm ./$(PROCESSO)

$(ESCALONADOR):
	cp $(PASTA_CODIGOS)/$(PASTA_GERAL)/$(PASTA_FILA)/$(FILA) ./
	cp $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(CPU) ./
	cp $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(PROCESSO) ./
	cp $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(TIPO_CPU) ./
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(ESCALONADOR) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	rm $(TIPO_CPU)
	rm $(PROCESSO)
	rm $(CPU)
	rm $(FILA)

$(PROCESSO): $(FILA)
	cp $(PASTA_CODIGOS)/$(PASTA_GERAL)/$(PASTA_FILA)/$(FILA) ./
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(PROCESSO) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	rm $(FILA)
	
$(CPU): $(PROCESSO) $(FILA)
	cp $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(PROCESSO) ./
	cp $(PASTA_CODIGOS)/$(PASTA_GERAL)/$(PASTA_FILA)/$(FILA) ./
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(CPU) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	rm $(PROCESSO)
	rm $(FILA)

$(TIPO_CPU):
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_ESCALONADOR)/$(TIPO_CPU) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)
	

$(ESCRITOR): 
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_GERAL)/$(PASTA_EntradaSaida)/$(ESCRITOR) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)

$(INTERFACE):
	$(COMPILADOR) $(PASTA_CODIGOS)/$(PASTA_INTERFACE)/$(INTERFACE) $(DEFINE_DIRETORIO_DE_COMPILADOS) $(PASTA_BINARIOS)